import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import mongoose from 'mongoose'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import crypto from 'crypto'
import Razorpay from 'razorpay'
import { body, validationResult } from 'express-validator'

const app=express(), PORT=process.env.PORT||5000
app.use(cors({origin:process.env.CLIENT_URL||'http://127.0.0.1:5173'})); app.use(express.json())
const id=()=>crypto.randomUUID(), sign=u=>jwt.sign({id:u._id,role:u.role},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||'7d'})
const auth=async(req,res,next)=>{try{let t=req.headers.authorization?.replace('Bearer ','');if(!t)throw Error('Missing token');req.user=jwt.verify(t,process.env.JWT_SECRET);next()}catch{res.status(401).json({message:'Authentication required'})}}
const admin=(req,res,next)=>req.user?.role==='admin'?next():res.status(403).json({message:'Admin access required'})
const valid=req=>{let e=validationResult(req);return e.isEmpty()?null:e.array().map(x=>x.msg)}

const addressSchema=new mongoose.Schema({name:String,phone:String,line1:String,city:String,state:String,postalCode:String,country:{type:String,default:'India'},isDefault:Boolean},{_id:true})
const User=mongoose.model('User',new mongoose.Schema({firstName:{type:String,required:true},lastName:{type:String,required:true},email:{type:String,required:true,unique:true,lowercase:true},password:{type:String,required:true,select:false},role:{type:String,enum:['customer','admin','vendor'],default:'customer'},phone:String,avatar:String,addresses:[addressSchema],resetToken:String,resetExpires:Date},{timestamps:true}))
const Product=mongoose.model('Product',new mongoose.Schema({name:{type:String,required:true},category:String,brand:String,description:String,image:String,stock:{type:Number,default:0},availability:{type:Boolean,default:true},pricing:{hourly:Number,daily:Number,weekly:Number,monthly:Number},variants:[{name:String,values:[String],required:Boolean}],securityDeposit:{type:Number,default:0},rating:{type:Number,default:0},active:{type:Boolean,default:true}},{timestamps:true}))
const Coupon=mongoose.model('Coupon',new mongoose.Schema({code:{type:String,unique:true,uppercase:true},discountType:{type:String,enum:['percentage','fixed'],default:'percentage'},discountValue:Number,minimumOrderValue:{type:Number,default:0},maximumDiscount:Number,expiryDate:Date,usageLimit:{type:Number,default:0},usageCount:{type:Number,default:0},active:{type:Boolean,default:true}},{timestamps:true}))
const Order=mongoose.model('Order',new mongoose.Schema({orderNumber:{type:String,unique:true},invoiceNumber:String,customer:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true},items:[{product:{type:mongoose.Schema.Types.ObjectId,ref:'Product'},name:String,variant:Object,quantity:Number,rentalStart:Date,rentalEnd:Date,rentalUnit:String,unitPrice:Number,rentalAmount:Number,securityDeposit:Number}],deliveryMethod:{type:String,enum:['delivery','pickup'],default:'delivery'},address:addressSchema,pickupStore:String,subtotal:Number,discount:Number,deliveryCharge:Number,securityDeposit:Number,totalAmount:Number,paymentStatus:{type:String,enum:['PENDING','PROCESSING','PAID','FAILED','REFUNDED'],default:'PENDING'},rentalStatus:{type:String,enum:['CONFIRMED','READY_FOR_PICKUP','PICKED_UP','ACTIVE','RETURN_DUE','OVERDUE','RETURNED','COMPLETED','CANCELLED'],default:'CONFIRMED'},depositStatus:{type:String,enum:['PENDING','HELD','PARTIALLY_REFUNDED','REFUNDED'],default:'PENDING'},lateFee:{type:Number,default:0},damageDeduction:{type:Number,default:0},refundAmount:{type:Number,default:0},razorpayOrderId:String,razorpayPaymentId:String,returnedAt:Date},{timestamps:true}))
const Quotation=mongoose.model('Quotation',new mongoose.Schema({number:String,customerName:String,items:[Object],subtotal:Number,deposit:Number,total:Number,status:{type:String,enum:['DRAFT','SENT','ACCEPTED','REJECTED','CONVERTED'],default:'DRAFT'},terms:String},{timestamps:true}))
const Setting=mongoose.model('Setting',new mongoose.Schema({key:{type:String,unique:true},value:mongoose.Schema.Types.Mixed}))
const periods={hourly:3600000,daily:86400000,weekly:604800000,monthly:2592000000}
const calculate=async(items,couponCode)=>{let subtotal=0,deposit=0,prepared=[];for(const i of items){let p=await Product.findById(i.productId);if(!p||!p.active||!p.availability||p.stock<i.quantity)throw Error(`Unavailable product: ${i.productId}`);let unit=i.rentalUnit||'daily',start=new Date(i.rentalStart),end=new Date(i.rentalEnd),count=Math.ceil((end-start)/periods[unit]);if(!periods[unit]||count<1||start<new Date(Date.now()-60000))throw Error('Invalid rental period');let rate=p.pricing[unit];if(!rate)throw Error(`No ${unit} price for ${p.name}`);let amount=rate*count*i.quantity;subtotal+=amount;deposit+=p.securityDeposit*i.quantity;prepared.push({product:p._id,name:p.name,variant:i.variant||{},quantity:i.quantity,rentalStart:start,rentalEnd:end,rentalUnit:unit,unitPrice:rate,rentalAmount:amount,securityDeposit:p.securityDeposit*i.quantity})}let discount=0;if(couponCode){let c=await Coupon.findOne({code:couponCode.toUpperCase(),active:true});if(!c||c.expiryDate&&c.expiryDate<new Date()||c.minimumOrderValue>subtotal)throw Error('Invalid coupon');discount=c.discountType==='fixed'?c.discountValue:Math.round(subtotal*c.discountValue/100);if(c.maximumDiscount)discount=Math.min(discount,c.maximumDiscount);if(c.usageLimit&&c.usageCount>=c.usageLimit)throw Error('Coupon usage limit reached');c.usageCount++;await c.save()}let deliveryCharge=0,totalAmount=subtotal+deposit+deliveryCharge-discount;return {items:prepared,subtotal,discount,securityDeposit:deposit,deliveryCharge,totalAmount}}
const transitions={CONFIRMED:['READY_FOR_PICKUP','CANCELLED'],READY_FOR_PICKUP:['PICKED_UP','CANCELLED'],PICKED_UP:['ACTIVE'],ACTIVE:['RETURN_DUE','OVERDUE','RETURNED'],RETURN_DUE:['RETURNED','OVERDUE'],OVERDUE:['RETURNED'],RETURNED:['COMPLETED']}

app.get('/api/health',(req,res)=>res.json({ok:true,service:'RentalFlow API'}))
app.post('/api/auth/register',[body('email').isEmail(),body('password').isStrongPassword(),body('firstName').trim().notEmpty(),body('lastName').trim().notEmpty()],async(req,res)=>{let e=valid(req);if(e)return res.status(422).json({errors:e});try{let u=await User.create({...req.body,email:req.body.email.toLowerCase(),password:await bcrypt.hash(req.body.password,12)});res.status(201).json({token:sign(u),user:{id:u._id,firstName:u.firstName,lastName:u.lastName,email:u.email,role:u.role}})}catch(e){res.status(409).json({message:e.code===11000?'Email already registered':'Unable to register'})}})
app.post('/api/auth/login',[body('email').isEmail(),body('password').notEmpty()],async(req,res)=>{let u=await User.findOne({email:req.body.email.toLowerCase()}).select('+password');if(!u||!await bcrypt.compare(req.body.password,u.password))return res.status(401).json({message:'Invalid email or password'});res.json({token:sign(u),user:{id:u._id,firstName:u.firstName,lastName:u.lastName,email:u.email,role:u.role}})})
app.post('/api/auth/forgot-password',[body('email').isEmail()],async(req,res)=>{let u=await User.findOne({email:req.body.email.toLowerCase()});if(!u)return res.json({message:'If the account exists, a reset link has been sent.'});let token=crypto.randomBytes(32).toString('hex');u.resetToken=crypto.createHash('sha256').update(token).digest('hex');u.resetExpires=new Date(Date.now()+3600000);await u.save();res.json({message:'Development reset token created.',developmentResetUrl:process.env.NODE_ENV==='production'?undefined:`/reset-password?token=${token}&email=${u.email}`})})
app.post('/api/auth/reset-password',[body('email').isEmail(),body('token').notEmpty(),body('password').isStrongPassword()],async(req,res)=>{let h=crypto.createHash('sha256').update(req.body.token).digest('hex'),u=await User.findOne({email:req.body.email,resetToken:h,resetExpires:{$gt:new Date()}}).select('+password');if(!u)return res.status(400).json({message:'Invalid or expired reset token'});u.password=await bcrypt.hash(req.body.password,12);u.resetToken=undefined;u.resetExpires=undefined;await u.save();res.json({message:'Password reset successful'})})
app.get('/api/auth/me',auth,async(req,res)=>res.json(await User.findById(req.user.id).select('-password -resetToken')))
app.put('/api/auth/me',auth,async(req,res)=>res.json(await User.findByIdAndUpdate(req.user.id,req.body,{new:true,runValidators:true}).select('-password')))

app.get('/api/products',async(req,res)=>{let q={active:true};for(const k of ['brand','category'])if(req.query[k])q[k]=req.query[k];if(req.query.available==='true')q.availability=true;let docs=await Product.find(q).sort('-createdAt');if(req.query.search){let r=new RegExp(req.query.search,'i');docs=docs.filter(p=>r.test(`${p.name} ${p.brand} ${p.category} ${p.description}`))}res.json(docs)})
app.get('/api/products/:id',async(req,res)=>{let p=await Product.findOne({_id:req.params.id,active:true});p?res.json(p):res.status(404).json({message:'Product not found'})})
app.post('/api/products',auth,admin,async(req,res)=>res.status(201).json(await Product.create(req.body)))
app.put('/api/products/:id',auth,admin,async(req,res)=>res.json(await Product.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true})))
app.delete('/api/products/:id',auth,admin,async(req,res)=>{await Product.findByIdAndUpdate(req.params.id,{active:false});res.status(204).end()})

app.post('/api/orders/quote',auth,async(req,res)=>{try{res.json(await calculate(req.body.items,req.body.couponCode))}catch(e){res.status(400).json({message:e.message})}})
app.post('/api/orders',auth,async(req,res)=>{try{let calc=await calculate(req.body.items,req.body.couponCode),o=await Order.create({...calc,customer:req.user.id,deliveryMethod:req.body.deliveryMethod,address:req.body.address,pickupStore:req.body.pickupStore,orderNumber:`ORD-${Date.now()}`,invoiceNumber:`INV-${Date.now()}`});res.status(201).json(o)}catch(e){res.status(400).json({message:e.message})}})
app.get('/api/orders',auth,async(req,res)=>{let q=req.user.role==='admin'?{}:{customer:req.user.id};if(req.query.status)q.rentalStatus=req.query.status;res.json(await Order.find(q).populate('customer','firstName lastName email').populate('items.product','name image').sort('-createdAt'))})
app.get('/api/orders/:id',auth,async(req,res)=>{let o=await Order.findById(req.params.id).populate('items.product');if(!o)return res.status(404).json({message:'Order not found'});if(req.user.role!=='admin'&&String(o.customer)!==req.user.id)return res.status(403).json({message:'Access denied'});res.json(o)})
app.patch('/api/orders/:id/status',auth,admin,async(req,res)=>{let o=await Order.findById(req.params.id),next=req.body.status;if(!o)return res.status(404).json({message:'Order not found'});if(!transitions[o.rentalStatus]?.includes(next))return res.status(400).json({message:`Invalid transition from ${o.rentalStatus} to ${next}`});o.rentalStatus=next;await o.save();res.json(o)})
app.post('/api/orders/:id/return',auth,admin,async(req,res)=>{let o=await Order.findById(req.params.id);if(!o)return res.status(404).json({message:'Order not found'});if(!['ACTIVE','RETURN_DUE','OVERDUE','PICKED_UP'].includes(o.rentalStatus))return res.status(400).json({message:'Order cannot be returned in current state'});let returnedAt=new Date(req.body.returnedAt||Date.now()),due=Math.max(...o.items.map(i=>new Date(i.rentalEnd))),days=Math.max(0,Math.ceil((returnedAt-due)/86400000)),lateFee=Math.min(o.securityDeposit,days*(req.body.dailyLateFee||100)),damage=Math.min(o.securityDeposit-lateFee,req.body.damageDeduction||0),refund=Math.max(0,o.securityDeposit-lateFee-damage);o.lateFee=lateFee;o.damageDeduction=damage;o.refundAmount=refund;o.returnedAt=returnedAt;o.depositStatus=refund===o.securityDeposit?'REFUNDED':refund?'PARTIALLY_REFUNDED':'PARTIALLY_REFUNDED';o.rentalStatus='COMPLETED';for(const item of o.items)await Product.findByIdAndUpdate(item.product,{$inc:{stock:item.quantity}});await o.save();res.json(o)})

const razorpay=()=>{if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)throw Error('Razorpay Test Mode is not configured');return new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET})}
app.post('/api/payments/create-order',auth,async(req,res)=>{try{let calc=await calculate(req.body.items,req.body.couponCode),r=await razorpay().orders.create({amount:Math.round(calc.totalAmount*100),currency:'INR',receipt:`rcpt_${Date.now()}`});res.json({razorpayOrderId:r.id,keyId:process.env.RAZORPAY_KEY_ID,amount:calc.totalAmount,calculation:calc})}catch(e){res.status(400).json({message:e.message})}})
app.post('/api/payments/verify',auth,async(req,res)=>{try{let {razorpay_order_id,razorpay_payment_id,razorpay_signature,orderId}=req.body,expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex');if(!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(razorpay_signature)))throw Error('Payment signature verification failed');let o=await Order.findOneAndUpdate({_id:orderId,customer:req.user.id,paymentStatus:{$ne:'PAID'}},{paymentStatus:'PAID',rentalStatus:'CONFIRMED',depositStatus:'HELD',razorpayOrderId:razorpay_order_id,razorpayPaymentId:razorpay_payment_id},{new:true});if(!o)throw Error('Order not found or already paid');for(const i of o.items)await Product.findByIdAndUpdate(i.product,{$inc:{stock:-i.quantity}});res.json({message:'Payment verified',order:o})}catch(e){res.status(400).json({message:e.message})}})

app.get('/api/admin/rental-board',auth,admin,async(req,res)=>{let q={};if(req.query.status)q.rentalStatus=req.query.status;let all=await Order.find(q).populate('customer','firstName lastName email').populate('items.product','name image').sort('createdAt');if(req.query.search){let r=new RegExp(req.query.search,'i');all=all.filter(o=>r.test(o.orderNumber)||r.test((o.customer?.firstName||'')+' '+(o.customer?.lastName||''))||o.items.some(i=>r.test(i.name)))}let now=new Date(),due=o=>o.items.some(i=>new Date(i.rentalEnd).toDateString()===now.toDateString()),pickups=all.filter(o=>o.rentalStatus==='READY_FOR_PICKUP'),returns=all.filter(o=>['RETURN_DUE','OVERDUE'].includes(o.rentalStatus));let columns={Reserved:all.filter(o=>['CONFIRMED','READY_FOR_PICKUP'].includes(o.rentalStatus)),Active:all.filter(o=>['PICKED_UP','ACTIVE','RETURN_DUE'].includes(o.rentalStatus)),Late:all.filter(o=>o.rentalStatus==='OVERDUE'),Completed:all.filter(o=>o.rentalStatus==='COMPLETED')};res.json({summary:{today:all.filter(due).length,pickups:pickups.length,returns:returns.length,late:columns.Late.length,sales:all.filter(o=>o.paymentStatus==='PAID').reduce((n,o)=>n+o.totalAmount,0),lateFees:all.reduce((n,o)=>n+o.lateFee,0),deposits:all.filter(o=>o.depositStatus==='HELD').reduce((n,o)=>n+o.securityDeposit,0)},list:all,kanban:columns})})
app.get('/api/admin/dashboard',auth,admin,async(req,res)=>{let all=await Order.find(),now=new Date(),same=d=>d&&new Date(d).toDateString()===now.toDateString(),active=all.filter(o=>['ACTIVE','PICKED_UP','OVERDUE'].includes(o.rentalStatus));res.json({activeRentals:active.length,dueToday:all.filter(o=>o.items.some(i=>same(i.rentalEnd))).length,upcomingPickups:all.filter(o=>o.rentalStatus==='READY_FOR_PICKUP').length,upcomingReturns:all.filter(o=>o.rentalStatus==='RETURN_DUE').length,overdueRentals:all.filter(o=>o.rentalStatus==='OVERDUE').length,rentalRevenue:all.filter(o=>o.paymentStatus==='PAID').reduce((n,o)=>n+o.totalAmount,0),securityDepositsHeld:all.filter(o=>o.depositStatus==='HELD').reduce((n,o)=>n+o.securityDeposit,0),lateFeeCollection:all.reduce((n,o)=>n+o.lateFee,0)})})
app.get('/api/admin/analytics',auth,admin,async(req,res)=>{let all=await Order.find();let rows={};all.forEach(o=>{let d=o.createdAt.toISOString().slice(0,10);rows[d]??={date:d,revenue:0,rentals:0,lateFees:0,deposits:0,refunds:0};rows[d].revenue+=o.paymentStatus==='PAID'?o.totalAmount:0;rows[d].rentals++;rows[d].lateFees+=o.lateFee;rows[d].deposits+=o.depositStatus==='HELD'?o.securityDeposit:0;rows[d].refunds+=o.refundAmount});res.json({trend:Object.values(rows),statuses:await Order.aggregate([{$group:{_id:'$rentalStatus',count:{$sum:1}}}]),products:await Order.aggregate([{$unwind:'$items'},{$group:{_id:'$items.product',rentals:{$sum:'$items.quantity'},revenue:{$sum:'$items.rentalAmount'}}},{$lookup:{from:'products',localField:'_id',foreignField:'_id',as:'product'}},{$unwind:'$product'},{$project:{name:'$product.name',rentals:1,revenue:1}}])})})
app.get('/api/admin/coupons',auth,admin,async(req,res)=>res.json(await Coupon.find().sort('-createdAt')));app.post('/api/admin/coupons',auth,admin,async(req,res)=>res.status(201).json(await Coupon.create(req.body)));app.put('/api/admin/coupons/:id',auth,admin,async(req,res)=>res.json(await Coupon.findByIdAndUpdate(req.params.id,req.body,{new:true})));app.delete('/api/admin/coupons/:id',auth,admin,async(req,res)=>{await Coupon.findByIdAndDelete(req.params.id);res.status(204).end()})
app.get('/api/admin/quotations',auth,admin,async(req,res)=>res.json(await Quotation.find().sort('-createdAt')));app.post('/api/admin/quotations',auth,admin,async(req,res)=>res.status(201).json(await Quotation.create({...req.body,number:`QUO-${Date.now()}`})));app.put('/api/admin/quotations/:id',auth,admin,async(req,res)=>res.json(await Quotation.findByIdAndUpdate(req.params.id,req.body,{new:true})))
app.get('/api/admin/settings',auth,admin,async(req,res)=>res.json((await Setting.findOne({key:'organization'}))?.value||{}));app.put('/api/admin/settings',auth,admin,async(req,res)=>res.json((await Setting.findOneAndUpdate({key:'organization'},{value:req.body},{upsert:true,new:true})).value))
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Unexpected server error'})})

async function seed(){if(await User.countDocuments())return;let hash=await bcrypt.hash('Customer@123',10),adminHash=await bcrypt.hash('Admin@123',10);await User.create([{firstName:'Demo',lastName:'Customer',email:'customer@demo.com',password:hash,role:'customer'},{firstName:'Avery',lastName:'Admin',email:'admin@demo.com',password:adminHash,role:'admin'}]);await Product.insertMany([{name:'Luxe Sectional Sofa',category:'Furniture',brand:'UrbanLiving',stock:8,availability:true,pricing:{hourly:75,daily:1800,weekly:8000,monthly:28000},securityDeposit:2000,rating:4.7},{name:'MacBook Pro 14',category:'Computers',brand:'Apple',stock:5,availability:true,pricing:{hourly:60,daily:1400,weekly:6500,monthly:24000},securityDeposit:3000,rating:4.8},{name:'Mirrorless Camera',category:'Cameras',brand:'Canon',stock:4,availability:true,pricing:{hourly:55,daily:1100,weekly:5000,monthly:18000},securityDeposit:2500,rating:4.6}]);await Coupon.create({code:'RENT10',discountType:'percentage',discountValue:10,active:true});console.log('Seeded demo users, products and coupon.')}
mongoose.connect(process.env.MONGODB_URI).then(async()=>{console.log('MongoDB connected');await seed();app.listen(PORT,()=>console.log(`RentalFlow API listening on http://localhost:${PORT}`))}).catch(e=>{console.error('MongoDB connection failed:',e.message);process.exit(1)})
